version = 0.1

[default.deploy.parameters]
stack_name = "feedback-platform"
resolve_s3 = true
s3_prefix = "feedback-platform"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
parameter_overrides = "AdminEmail=\"admin@example.com\" SenderEmail=\"noreply@example.com\""
