quarkus.dynamodb.endpoint-override=http://arn:aws:dynamodb:us-east-1:534781021867:table/feedback

quarkus.dynamodb.aws.region=us-east-1
quarkus.dynamodb.aws.credentials.type=static
quarkus.dynamodb.aws.credentials.static-provider.access-key-id=admin
quarkus.dynamodb.aws.credentials.static-provider.secret-access-key=admin